### ISSUE TITLE
Updating the com.google.guava:guava dependency to v33.4.5-jre fails.

### ISSUE THREAD

**Issue by jlerbsc** [javaparser/javaparser#4697]
When updating the version of guava from 33.4.0 to 33.4.5 the compilation of the project fails with a ‘cannot find symbol Error: symbol: class NonNull’ or ‘cannot find symbol symbol: class CheckForNull’ error

This link probably explains the cause of the error.

https://github.com/google/guava/issues/2960
